CREATE DATABASE UNIVERSITY;

USE UNIVERSITY;

CREATE TABLE SCHOOL (
    SchoolId INT NOT NULL PRIMARY KEY,
    SchoolName VARCHAR(50) NOT NULL,
    Description VARCHAR(1000),
    Address VARCHAR(50),
    Phone VARCHAR(50),
    PostCode VARCHAR(50),
    PostAddress VARCHAR(50)
);

CREATE TABLE CLASS (
    ClassId INT NOT NULL PRIMARY KEY,
    SchoolId INT NOT NULL,
    ClassName VARCHAR(50) NOT NULL,
    Description VARCHAR(1000),
    FOREIGN KEY (SchoolId) REFERENCES SCHOOL(SchoolId)
);

CREATE TABLE COURSE (
    CourseId INT NOT NULL PRIMARY KEY,
    CourseName VARCHAR(50) NOT NULL,
    SchoolId INT NOT NULL,
    Description VARCHAR(1000),
    FOREIGN KEY (SchoolId) REFERENCES SCHOOL(SchoolId)
);


CREATE TABLE STUDENT (
    StudentId INT NOT NULL PRIMARY KEY,
    ClassId INT NOT NULL,
    StudentName VARCHAR(50) NOT NULL,
    StudentNumber VARCHAR(20) NOT NULL,
    TotalGrade FLOAT,
    Address VARCHAR(100),
    Phone VARCHAR(20),
    EMail VARCHAR(100),
    FOREIGN KEY (ClassId) REFERENCES CLASS(ClassId)
);

CREATE TABLE STUDENT_COURSE (
    StudentId INT NOT NULL,
    CourseId INT NOT NULL,
    PRIMARY KEY (StudentId, CourseId),
    FOREIGN KEY (StudentId) REFERENCES STUDENT(StudentId),
    FOREIGN KEY (CourseId) REFERENCES COURSE(CourseId)
);
CREATE TABLE TEACHER (
    TeacherId INT NOT NULL PRIMARY KEY,
    SchoolId INT NOT NULL,
    TeacherName VARCHAR(50) NOT NULL,
    Description VARCHAR(1000),
    FOREIGN KEY (SchoolId) REFERENCES SCHOOL(SchoolId)
);

CREATE TABLE TEACHER_COURSE (
    TeacherId INT NOT NULL,
    CourseId INT NOT NULL,
    PRIMARY KEY (TeacherId, CourseId),
    FOREIGN KEY (TeacherId) REFERENCES TEACHER(TeacherId),
    FOREIGN KEY (CourseId) REFERENCES COURSE(CourseId)
);

CREATE TABLE GRADE (
    GradeId INT NOT NULL PRIMARY KEY,
    StudentId INT NOT NULL,
    CourseId INT NOT NULL,
    Grade FLOAT NOT NULL,
    Comment VARCHAR(1000),
    FOREIGN KEY (StudentId) REFERENCES STUDENT(StudentId),
    FOREIGN KEY (CourseId) REFERENCES COURSE(CourseId)
);